#!/bin/bash -e

echocol() { echo -e "\033[31m*** $@...\033[0m"; }

tests="simple"

if [[ -n "$xTRAVIS" ]]; then
	echocol "Installing and configuring mercurial (we are on travis)"
	virtualenv /tmp/test
	. /tmp/test/bin/activate
	pip install mercurial
	cat >~/.hgrc <<EOF
[ui]
username = Test User <test@foo.bar>
[extensions]
bookmarks =
rebase =
EOF
fi


for t in $tests; do
	echocol $t
	./test/$t
done
