#!/bin/bash -e

echocol() { echo -e "\033[31m*** $@...\033[0m"; }

tests="simple"

if [[ ! -r ~/.hgrc ]]; then
	echocol "Configuring mercurial"
	cat >~/.hgrc <<EOF
[ui]
username = Test User <test@foo.bar>
[extensions]
bookmarks =
rebase =
EOF
fi


for t in $tests; do
	echocol $t
	./test/$t
done
