#!/bin/bash -e

TMPDIR=$(mktemp -d /tmp/squash-XXXXXX) || exit 1
WORK="$TMPDIR/work"
PUBLIC="$TMPDIR/public"

hg init "$WORK"

V=0
echo $V > "$WORK/file.txt"
hg -R "$WORK" add "$WORK/file.txt"
hg -R "$WORK" ci -m"Version $V"

V=$((V+1)); echo $V > "$WORK/file.txt"; hg -R "$WORK" ci -m"Version $V"
V=$((V+1)); echo $V > "$WORK/file.txt"; hg -R "$WORK" ci -m"Version $V"
V=$((V+1)); echo $V > "$WORK/file.txt"; hg -R "$WORK" ci -m"Version $V"

./hg-sap "$WORK" "$PUBLIC"

V=$((V+1)); echo $V > "$WORK/file.txt"; hg -R "$WORK" ci -m"Version $V"
V=$((V+1)); echo $V > "$WORK/file.txt"; hg -R "$WORK" ci -m"Version $V"
V=$((V+1)); echo $V > "$WORK/file.txt"; hg -R "$WORK" ci -m"Version $V"

./hg-sap "$WORK" "$PUBLIC"

V=$((V+1)); echo $V > "$WORK/file.txt"; hg -R "$WORK" ci -m"Version $V"
V=$((V+1)); echo $V > "$WORK/file.txt"; hg -R "$WORK" ci -m"Version $V"
V=$((V+1)); echo $V > "$WORK/file.txt"; hg -R "$WORK" ci -m"Version $V"

./hg-sap "$WORK" "$PUBLIC"

V=$((V+1)); echo $V > "$WORK/file.txt"; hg -R "$WORK" ci -m"Version $V"
V=$((V+1)); echo $V > "$WORK/file.txt"; hg -R "$WORK" ci -m"Version $V"
V=$((V+1)); echo $V > "$WORK/file.txt"; hg -R "$WORK" ci -m"Version $V"
V=$((V+1)); echo $V > "$WORK/file.txt"; hg -R "$WORK" ci -m"Version $V"

./hg-sap -v "$WORK" "$PUBLIC"

rm -rf "$TMPDIR"
