#!/bin/bash -e

TMPDIR=$(mktemp -d /tmp/squash-XXXXXX) || exit 1

WORK="$TMPDIR/work"
PUBLIC="$TMPDIR/public"
REVS="$TMPDIR/revs.txt"

echocol() { echo -e "\033[32m*** $@...\033[0m"; }

. ./test/functions

init() {
	V=0
	hg init "$WORK"
	echo $V > "$WORK/file.txt"
	hg -R "$WORK" add "$WORK/file.txt"
	hg -R "$WORK" ci -m"Version $V"
}

simplework() {
	V=$((V+1))
	echo $V > "$WORK/file.txt"
	hg -R "$WORK" ci -m"Version $V"
}

### doit

echocol "Performing some work"

init

simplework
simplework
simplework

./hg-sap "$WORK" "$PUBLIC"
echo -e "$(tip_node "$WORK")\t$(tip_node "$PUBLIC")" >> "$REVS"

simplework

./hg-sap "$WORK" "$PUBLIC"
echo -e "$(tip_node "$WORK")\t$(tip_node "$PUBLIC")" >> "$REVS"

simplework
simplework
simplework
simplework

./hg-sap "$WORK" "$PUBLIC"
echo -e "$(tip_node "$WORK")\t$(tip_node "$PUBLIC")" >> "$REVS"

### show

echocol "Inspecting repos"

inspect_repo "$WORK"
inspect_repo "$PUBLIC"

### testit

echocol "Testing repo differences"

cat "$REVS" | while read src dst; do
	compare_repos "$WORK" "$src" "$PUBLIC" "$dst"
done

rm -rf "$TMPDIR"
